export class DatosAfipDataView {
    ctg: number;
    solicitante: string;
    cartaPorte: number;
    estado: string;
    fechaEmision: string;
    fechaVigenciaDesde: string;
    fechaVigenciaHasta: string;
    cuitCanjeador: string;
    canjeadorComoRemitenteComercial: string;
    especie: string;
    cuitDestino: string;
    cuitDestinatario: string;
    establecimiento: number;
    localidadOrigen: string;
    localidadDestino: string;
    cosecha: string;
    cuitTransportista: string;
    detalle: string;
    cantidadHoras: number;
    patenteVehiculo: string;
    pesoNetoCarga: number;
    kmARecorrer: number;
    tarifaReferencia: number;
    fechaHoraConfirmacionDefinitiva: string;
    ctcCodigo: string;
    cuitCorredor: number;
    turno: string;
}
