import { Entity } from '../../core/models/entity';
import { MotivoNoDescarga } from './situacion-entrada/lista-motivos-no-descarga/motivo-no-descarga';
import { Producto } from '../../shared/data-models/producto';

export class MovimientoPesaje extends Entity {
    idTerminal: number;
    idTipoMovimiento: number;
    producto: Producto;
    esControlPesoInterno: boolean;
    esSuPrimeraVez: boolean;
    idTipoTransporte: number;
    idTipoProducto: number;
    idEstado: number;
    cosecha: string;
    idCircuito: number;
    tipoDocumentoPorte: string;
    nroDocumentoPorte: string;
    ctg: number;
    turno: string;
    version: string;
    estadoCupo: string;
    estado: string;
    ordenCompra: string;
    ordenCarga: string;
    humedad: number;
    proteina: number;
    grado: number;
    gradoDescripcion: string;
    cantidadEstimada: number;
    kgPesoBrutoDocumento: number;
    kgPesoBruto: number;
    kgPesoTara: number;
    kgPesoNetoDocumento: number;
    kgPesoTaraDocumento: number;
    pesaEntrada: boolean;
    esDescarga: boolean;
    motivosIngreso: MotivoNoDescarga[];
    motivosEgreso: MotivoNoDescarga[];
    patente: string;
    numeroVagon: number;
    tarjeta: string;
    coeficienteConversionLitros: number;
    fechaStockSAN: Date;
    entradaEsRepesaje: boolean;
    salidaEsRepesaje: boolean;
    entradaManualAutomatico: string;
    salidaManualAutomatico: string;
    lugarDescargaCarga: string;
    entregador: string;
    kgPesoAnterior: number;
    fueExitoso: boolean;
    esInsumoLiquidoRechazado: boolean;
    imputaStockLitros: boolean;
    cargoConError: number;
    idCondicionManipuleo: number;
}
