export class ModificarParametrosPorTerminalCommand  {
  public Id: number;
  public direccion: string;
  public IdTipoTarjeta: number;
  public IdSede: number;
  public abreviatura: string;
  public utilizaTarjeta: boolean;
  public copiasTicketCalidadVagon: number;
  public copiasTicketCalidad: number;
  public copiasTicketPesaje: number;
  public copiasRemito: number;
  public diferenciaDiasFiltroControlPeso: number;
  public diferenciaDiasFiltroGeneracionArchivoMuestra: number;
  public horaCorteCupo: string;
  public kgsBrutosEstimados: number;
  public kgsTaraEstimados: number;
  public horasExpiracionRespuestaEntregador: number;
  public IdRolAutorizadorControl: number;
  public IdDestinatarioPorDefecto: number;
  public codigosBarras: number[];
  public expresionesRegularPatente: number[];
  public leyendaBonificacionTrigo: boolean;
  public usaFleteCorto: boolean;
  public usaMuestraIntacta: boolean;
  public usaAceptarYContinuar: boolean;
  public codigoAduana: string;
  public nroLote: string;
  public toleranciaTurnoCircular: number;
}
